# specify a base image
# Note: 16-alpine used to avoid bugs!
FROM node:16-alpine

# user will be the node user, not the default of root
USER node

# We are then creating a directory of /home/node/app prior to the 
# WORKDIR instruction. This will prevent a permissions issue since 
# WORKDIR by default will create a directory if it does not exist 
# and set ownership to root.
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# The inline chown commands will set ownership of the files you are 
# copying from your local environment to the node user in the container.
# The end result is that some files and directories will no longer be 
# owned by root, and no npm processes will be run by the root user. 
# Instead, they will all be owned and run by the node user.
COPY --chown=node:node ./package.json ./

# Download and install all required dependencies.
RUN npm install

# now we can copy all files over from the working dir to the container.
# Again setting the user to node prior to the copy command.
COPY --chown=node:node ./ ./

# default command
CMD ["npm", "start"]

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true 
# The core of the issue was the volume bookmarking (placeholder) 
# was created by root. As a result, the node_modules will be owned 
# by root. As part of the development process, the Webpack / Babel 
# Loader will attempt to create a node_modules.cache folder as the 
# Node user. In Node 15, 16+, this will result in a EACCES: permission denied.